### PR TITLE
Add argument for bootstrap and warning for running it with localhost …

### PR DESCRIPTION
**Pull request by mostekcm**
…instead

### CODE REVIEW

**Review by hous — APPROVED** [review]

**Comment by hous** [comment]
@mostekcm - FYI I'm not able to merge this because the commits aren't signed - any way you can recreate with commit signing?

**Review by hous — COMMENTED** [review]
LGTM

**Comment by hous** [comment]
@mostekcm I still can't merge this due to commit signing rules.

**Comment by matthewpereira** [comment]
Closing this in favor of #55 which recreates this approach with some added messaging.

**Pull request closed without merging**
